name: Lint and Testing

on:
  push:
  pull_request:

permissions:
  actions: read
  contents: read
  statuses: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          args: --verbose

  testing:
    runs-on: ubuntu-latest
    container: golang:1.23-alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: add git make command
        run: |
          apk add git make curl perl bash build-base zlib-dev ucl-dev

      - name: testing
        run: |
          make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
